### ISSUE TITLE
When run SampleApp goes to break mode!

### ISSUE THREAD

**Issue by HamidEbr** [cesarsouza/keras-sharp#11]
Thanks for your good codes!
I can compiled all codes successfully but when start SampleApp, it`s started in break mode and when continue, stopped!

**Comment by cesarsouza** [comment]
Hi @HamidEbr,

Thanks for opening the issue! However, the sample app is not ready yet - the project is still in a very early stage at this moment.

Regards,
Cesar

**Comment by HamidEbr** [comment]
Exclent! Hope doing well!

**Comment by cesarsouza** [comment]
Hi @HamidEbr!

Just to give a small update: It should now be possible to learn simple MLPs using Keras#. I've just added an example to the [project's main page](https://github.com/cesarsouza/keras-sharp). Support for more complex models should follow shortly, since right now most of the engine code is in place.

**Comment by HamidEbr** [comment]
Well done!

**Comment by cesarsouza** [comment]
For the moment the sample application will by default be set to use the TensorFlow backend since it currently works better. The sample application doesn't go to break mode just out-of-the-box as it was the case before, so I will be closing this issue, and address the CNTK-related issue at #13.
